### ISSUE TITLE
Mini-format for adresser og adgangsadresser

### ISSUE THREAD

**Issue by andershessellund** [DanmarksAdresser/Dawa#331]
Det kunne give mening at implementere et mini-format for adresser og adgangsadresser.

Mini-formatet skulle indeholde de mest hyppigt anvendte felter. 

Formålet er, at klienter ikke behøver at hente mere data end nødvendigt. Dette vil dels begrænse belastning på serveren, dels vil det også medføre mindre downloads og trafik til klienten. Et JSON-formatteret adresseudtræk fylder i forvejen ~1GB, så en reduktion er velkomment. Derudover kan mobile klienter have begrænset båndbredde.

Forslag til inkluderede felter:
status, kommunekode, vejkode, vejnavn, husnr, etage, dør, supplerende bynavn, postnr, postnr navn, koordinater.

Det betyder, at følgende felter udelades:
ejerlav, matrikelnr, esrejendomsnummer, metadata om adgangspunktet, kommunenavn, DAGI-temaer, DDKN, zone.

Åbne spørgsmål: 
1) Skal href felterne være med (href til vejstykke, supplerende bynavn, kommune, postnr, adgangsadresse, adressen selv)? Formålet med mini-formatet er at det skal være effektivt. href felterne er ikke decideret nødvendige. Jeg hælder til at de ikke skal være med.
2) Skal mini-formatet være et "fladt" format? Det giver simplere kode (samme kodebase for CSV og JSON, og GeoJSON). Værdien ved at have et format med nestede objekter er måske begrænset. Jeg hælder til et fladt format.
3) Vi har allerede et autocomplete format. Måske skulle man løse op, så man både på autocomplete, almindelige queries og enkeltopslag frit kan vælge mellem de tre repræsentationer (full, autocomplete, mini) og de tre serialiseringsformater  (CSV, JSON og GeoJSON)? Dette vil rent kodemæssigt være let at implementere. Jeg synes det ville være en god løsning.

**Comment by finnjordal** [comment]
Ønske om miniformat: https://digitaliser.dk/forum/3180730#comment_3180731
