### ISSUE TITLE
Fejl ved adressesøgning på status. Antal ved status=1: 817201og ved status=3:  6058. Det giver ikke ca 3.5 mio til sammen

### ISSUE THREAD

**Issue by finnjordal** [DanmarksAdresser/Dawa#355]

**Comment by jakobfaerch** [comment]
Det virker for søgning på adgangsadresser

**Comment by jakobfaerch** [comment]
Jeg synes ikke rigtig jeg kan reproducere, jeg får

jrf ~/Documents/dev/Dawa [master*]$ curl "http://dawa.aws.dk/adresser?status=3&format=csv"|wc -l
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3223k    0 3223k    0     0   883k      0 --:--:--  0:00:03 --:--:--  883k
    6116
jrf ~/Documents/dev/Dawa [master*]$ curl "http://dawa.aws.dk/adresser?status=1&format=csv" > dawa-prod-355-status1.csv
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1761M    0 1761M    0     0  1049k      0 --:--:--  0:28:37 --:--:-- 1225k
jrf ~/Documents/dev/Dawa [master*]$ wc -l dawa-prod-355-status1.csv
 3435986 dawa-prod-355-status1.csv

Dvs. i alt (6116-1 + 3435986 -1) = 3.442.100

Som er det forventede antal adresser i alt.

Kan du prøve at reproducere det igen? Det tog min curl 28:37 at streame de 3,4 mio status 1'ere over, kan der have været et hik et sted da du forsøgte, som har fået requesten til at fejle uden at din line count opdagede det?

**Comment by finnjordal** [comment]
Jo, det må være. Jeg havde dog forventet, at jeg ville have fået en fejlmeddelse.
Men det ser ud til at virke, så jeg fører den over i done.

**Comment by jakobfaerch** [comment]
Ja, det er lidt mærkeligt. Hvis jeg slukker for min lokale Dawa-server mens curl er ved at streame, får jeg dette:

jrf ~/Documents/dev/Dawa [master*]$ curl -S "http://localhost:3000/adresser?status=1&format=csv"|wc -l
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3222k    0 3222k    0     0  1910k      0 --:--:--  0:00:01 --:--:-- 1910kcurl: (18) transfer closed with outstanding read data remaining
    9115

Hvor curl: (18) transfer closed...
betyder at curl opdagede at noget gik galt. Wc er selvfølgelig ligeglad, så den tæller bare hvad den nåede at få.
