### ISSUE TITLE
Enhedsadresser uden adgangsadresse

### ISSUE THREAD

**Issue by jrftrifork** [DanmarksAdresser/Dawa#356]
Error report:

Fra: Andon Dragomanov [mailto:ad@mca.mk] 
Sendt: 17. januar 2015 15:50
Til: MBBL AWS Suiten Postkasse
Emne: AWS db incosistencies
 
Hi Finn,
 
Please find the error attached that a dev found when replicating the DAWA locally.
 
Generally the issue is that there are 19 addresses that do not have a access address.
It would be nice to clean them off such that we don't have to query the database with additional checks to eliminate these items - for performance reasons. Plus it would be nice to have a consistent DB on your end.
 
And just an idea ... your service would be quite cool if you join forces with virk.dk and somehow merge the WebAPI. We do that for some of our clients, but it would be nice if it was open to the public.
 
Have a nice weekend...And thanks again for AWS! 
Kind Regards,
Andon Dragomanov

**Comment by jakobfaerch** [comment]
Vedhæftet fil til fejlrapport indeholder:
note: the database tables locally are renamed to Address and AddressAccess
the following quesry:
select * from [Address] where adgangsadresseid not in (select id from [AddressAccess])
returns: 

id                                   adgangsadresseid                     oprettet                ikraftfra               aendret                 etage                                              doer
------------------------------------ ------------------------------------ ----------------------- ----------------------- ----------------------- -------------------------------------------------- --------------------------------------------------
6BE2D57C-F4EB-4894-9A2C-36A2F3355801 AE6D28E6-9A8F-4ADC-BED7-C65FA135116B 2000-02-05 15:22:00     NULL                    2000-02-18 23:18:00     NULL                                               NULL
F748122F-4123-48EE-91F0-DF2EA981A693 E5AD96FD-FA49-4125-815F-30F90C82DD68 2005-12-01 17:12:00     NULL                    2005-12-01 17:12:00     NULL                                               NULL
9FD5E84C-A638-4179-9E9B-E6D15C8A06EA 3CA98F0C-007C-49AA-8AC3-5C151A574C59 2000-02-05 15:22:00     NULL                    2000-02-18 23:18:00     NULL                                               NULL
557BDED4-692A-4D23-9B14-7417C8F46463 DCD74992-8722-451C-81BC-B1E15DE64F41 2005-12-01 17:09:00     NULL                    2005-12-01 17:09:00     NULL                                               NULL
FC240C14-8B67-4A14-A7C0-86DA9CA2EF18 295B5B30-C84D-4612-B023-63CA17FA81DB 2000-02-05 23:30:00     NULL                    2000-02-16 22:14:00     NULL                                               NULL
8777F6A7-3F55-496D-BC26-ACC91B75EB65 0D21F97F-B499-4269-BE35-2427F5DC5B7D 2000-02-05 15:20:00     NULL                    2000-02-18 23:18:00     NULL                                               NULL
62996C51-07B9-4AE5-84A8-BEC5123132FC 41281F60-5451-4C57-8D0D-C2099D4D9649 2003-12-01 16:14:00     NULL                    2003-12-01 16:14:00     NULL                                               NULL
AAF2E4A6-0BDB-44AF-80B8-C217C1F1C905 C38B6D08-FB71-48E0-8B2F-F3E3B80BD30F 2009-10-06 11:48:00     NULL                    2009-10-06 11:49:00     NULL                                               NULL
8BFC8734-5537-46B7-A914-D7743E35F91D FA8A8DE8-FDAE-4395-BEE7-04EC6453714D 2005-12-01 16:54:00     NULL                    2005-12-01 16:54:00     NULL                                               NULL
9FAF69B8-BA59-407B-BCF6-093939E68A8B 5365A406-0621-4788-AE62-412D6E5266DA 2005-12-01 17:03:00     NULL                    2005-12-01 17:03:00     NULL                                               NULL
49E67ADA-60FB-4616-81E9-1FBED0DA2D98 2E4CCEE0-EF5E-467D-A4B8-6373C32A9361 2004-02-12 13:30:00     NULL                    2004-02-12 13:30:00     NULL                                               NULL
E52EDAA2-6581-40AE-990A-F07F2420A294 0AFD6850-7562-44B8-BEFE-53DB7968B225 2005-12-01 16:47:00     NULL                    2005-12-01 16:47:00     NULL                                               NULL
253343BF-E19E-41FF-911E-BEF6395C0AEF D8D3EF8D-4C7B-4453-8699-8D37F39A0DCE 2000-02-05 20:32:00     NULL                    2000-02-17 20:45:00     NULL                                               NULL
85C796C8-1B74-4F0A-872F-62856120C9E1 BE075866-45FC-46F8-AC0F-F084C845019D 2011-07-28 09:56:00     NULL                    2011-07-28 09:56:00     NULL                                               NULL
F3879390-305C-4E26-BDD8-813B0D94B93C 92360BE3-A39A-4142-AA0F-AE0AD41EC2CF 2000-02-05 21:04:00     NULL                    2000-02-16 22:12:00     NULL                                               NULL
2538530A-95D5-445D-A7FD-915568CB3D98 2F58E71A-828C-45B6-B399-FED5DEDAE5C9 2000-02-05 20:38:00     NULL                    2000-02-17 20:48:00     NULL                                               NULL
1767DAC9-6C05-4B33-B699-A1AF01887F5A 6A32256B-218D-4A1F-8424-F2008D62640C 2000-02-05 21:12:00     NULL                    2000-02-16 22:13:00     NULL                                               NULL
B5CEF73C-8960-4062-B360-153549B08AAA F929EF27-6361-4B25-BD3C-BF9FAD1F2C0C 2000-02-05 15:20:00     NULL                    2000-02-18 23:18:00     NULL                                               NULL
1C8DB50F-9531-4057-8D63-B50DB80FC94C C9449A1C-99D1-49E0-9A2E-8A6A0222A274 2000-02-05 19:31:00     NULL                    2000-02-16 22:13:00     NULL                                               NULL

(19 row(s) affected)

Using http://dawa.aws.dk/adgangsadresser/AE6D28E6-9A8F-4ADC-BED7-C65FA135116B for the first row i get
{
  "type": "ResourceNotFoundError",
  "title": "The resource was not found",
  "details": {
    "id": "5365A406-0621-4788-AE62-412D6E5266DA"
  }
}
Same for http://dawa.aws.dk/adresser/6BE2D57C-F4EB-4894-9A2C-36A2F3355801 for the first row' id (Address)
{
  "type": "ResourceNotFoundError",
  "title": "The resource was not found",
  "details": {
    "id": "6BE2D57C-F4EB-4894-9A2C-36A2F3355801"
  }
}

**Comment by jakobfaerch** [comment]
The output is consistent with what I see in the DAWA code. But the responses from the replication API is clearly not consistent and should be changed. We must start by finding out whether it's a bug in our code or an inconsitency in our source data.

I have run this query corresponding to Andon's against a not entirely recent copy of our production database:
SELECT e.id, e.adgangsadresseid FROM enhedsadresser e left join adgangsadresser a on e.adgangsadresseid=a.id where a.id is null

It returns

e52edaa2-6581-40ae-990a-f07f2420a294,0afd6850-7562-44b8-befe-53db7968b225
8777f6a7-3f55-496d-bc26-acc91b75eb65,0d21f97f-b499-4269-be35-2427f5dc5b7d
fc240c14-8b67-4a14-a7c0-86da9ca2ef18,295b5b30-c84d-4612-b023-63ca17fa81db
49e67ada-60fb-4616-81e9-1fbed0da2d98,2e4ccee0-ef5e-467d-a4b8-6373c32a9361
2538530a-95d5-445d-a7fd-915568cb3d98,2f58e71a-828c-45b6-b399-fed5dedae5c9
9fd5e84c-a638-4179-9e9b-e6d15c8a06ea,3ca98f0c-007c-49aa-8ac3-5c151a574c59
62996c51-07b9-4ae5-84a8-bec5123132fc,41281f60-5451-4c57-8d0d-c2099d4d9649
9faf69b8-ba59-407b-bcf6-093939e68a8b,5365a406-0621-4788-ae62-412d6e5266da
1767dac9-6c05-4b33-b699-a1af01887f5a,6a32256b-218d-4a1f-8424-f2008d62640c
f3879390-305c-4e26-bdd8-813b0d94b93c,92360be3-a39a-4142-aa0f-ae0ad41ec2cf
6be2d57c-f4eb-4894-9a2c-36a2f3355801,ae6d28e6-9a8f-4adc-bed7-c65fa135116b
85c796c8-1b74-4f0a-872f-62856120c9e1,be075866-45fc-46f8-ac0f-f084c845019d
aaf2e4a6-0bdb-44af-80b8-c217c1f1c905,c38b6d08-fb71-48e0-8b2f-f3e3b80bd30f
1c8db50f-9531-4057-8d63-b50db80fc94c,c9449a1c-99d1-49e0-9a2e-8a6a0222a274
253343bf-e19e-41ff-911e-bef6395c0aef,d8d3ef8d-4c7b-4453-8699-8d37f39a0dce
557bded4-692a-4d23-9b14-7417c8f46463,dcd74992-8722-451c-81bc-b1e15de64f41
f748122f-4123-48ee-91f0-df2ea981a693,e5ad96fd-fa49-4125-815f-30f90c82dd68
b5cef73c-8960-4062-b360-153549b08aaa,f929ef27-6361-4b25-bd3c-bf9fad1f2c0c
8bfc8734-5537-46b7-a914-d7743e35f91d,fa8a8de8-fdae-4395-bee7-04ec6453714d

Where the adgangsadresse id's match the ones found by Andon.

The http://dawa.aws.dk/adgangsadresser/ queries return HTTP 404 because the online query interface queries a special view where the adgangsadresse information is (inner) joined on the enhedsadresse rows.

**Comment by jakobfaerch** [comment]
Finn Jordal skriver 21/1-2015:
"Jeg har nu forsket lidt i de 19 enhedsadresser uden adgangsadresser. Data i BBR viser at adgangsadresserne er nedlagte og derved ikke overført til AWS 4. KMD er nu informeret om problemstillingen og jeg venter at de foreslår en løsning.
 
Jeg har ved lagt en CSV-fil med de 19 adresser med status og datoer."


CSV-filens indhold er:
ˇ˛EnhedsAdresseId_Value,ObjektType_Value,EnhedsAdresseOpretTimestamp_Value,EnhedsAdresseAendretTimestamp_Value,EnhedsAdresseOphoertTimestamp_Value,AdgangsAdresseId_Value,ObjektType_Value2,AdgangsAdresseOpretTimestamp_Value,AdgangsAdresseAendretTimestamp_Value,AdgangsAdresseOphoertTimestamp_Value,TotalRows

1767dac9-6c05-4b33-b699-a1af01887f5a,3,2/5/2000,2/16/2000,,6a32256b-218d-4a1f-8424-f2008d62640c,3,2/5/2000,6/3/2014,6/3/2014,Total rows: 19

1c8db50f-9531-4057-8d63-b50db80fc94c,3,2/5/2000,2/16/2000,,c9449a1c-99d1-49e0-9a2e-8a6a0222a274,3,2/5/2000,6/3/2014,6/3/2014,Total rows: 19

253343bf-e19e-41ff-911e-bef6395c0aef,3,2/5/2000,2/17/2000,,d8d3ef8d-4c7b-4453-8699-8d37f39a0dce,3,2/5/2000,5/5/2014,5/5/2014,Total rows: 19

2538530a-95d5-445d-a7fd-915568cb3d98,3,2/5/2000,2/17/2000,,2f58e71a-828c-45b6-b399-fed5dedae5c9,3,2/5/2000,5/5/2014,5/5/2014,Total rows: 19

49e67ada-60fb-4616-81e9-1fbed0da2d98,3,2/12/2004,2/12/2004,,2e4ccee0-ef5e-467d-a4b8-6373c32a9361,3,2/12/2004,6/3/2014,6/3/2014,Total rows: 19

557bded4-692a-4d23-9b14-7417c8f46463,3,12/1/2005,12/1/2005,,dcd74992-8722-451c-81bc-b1e15de64f41,3,12/1/2005,6/3/2014,6/3/2014,Total rows: 19

62996c51-07b9-4ae5-84a8-bec5123132fc,3,12/1/2003,12/1/2003,,41281f60-5451-4c57-8d0d-c2099d4d9649,3,12/1/2003,6/3/2014,6/3/2014,Total rows: 19

6be2d57c-f4eb-4894-9a2c-36a2f3355801,3,2/5/2000,2/18/2000,,ae6d28e6-9a8f-4adc-bed7-c65fa135116b,3,2/5/2000,6/3/2014,6/3/2014,Total rows: 19

85c796c8-1b74-4f0a-872f-62856120c9e1,3,7/28/2011,7/28/2011,,be075866-45fc-46f8-ac0f-f084c845019d,3,8/16/2002,5/5/2014,5/5/2014,Total rows: 19

8777f6a7-3f55-496d-bc26-acc91b75eb65,3,2/5/2000,2/18/2000,,0d21f97f-b499-4269-be35-2427f5dc5b7d,3,2/5/2000,6/3/2014,6/3/2014,Total rows: 19

8bfc8734-5537-46b7-a914-d7743e35f91d,3,12/1/2005,12/1/2005,,fa8a8de8-fdae-4395-bee7-04ec6453714d,3,12/1/2005,6/3/2014,6/3/2014,Total rows: 19

9faf69b8-ba59-407b-bcf6-093939e68a8b,3,12/1/2005,12/1/2005,,5365a406-0621-4788-ae62-412d6e5266da,3,12/1/2005,6/3/2014,6/3/2014,Total rows: 19

9fd5e84c-a638-4179-9e9b-e6d15c8a06ea,3,2/5/2000,2/18/2000,,3ca98f0c-007c-49aa-8ac3-5c151a574c59,3,2/5/2000,6/3/2014,6/3/2014,Total rows: 19

b5cef73c-8960-4062-b360-153549b08aaa,3,2/5/2000,2/18/2000,,f929ef27-6361-4b25-bd3c-bf9fad1f2c0c,3,2/5/2000,6/3/2014,6/3/2014,Total rows: 19

e52edaa2-6581-40ae-990a-f07f2420a294,3,12/1/2005,12/1/2005,,0afd6850-7562-44b8-befe-53db7968b225,3,12/1/2005,6/3/2014,6/3/2014,Total rows: 19

f3879390-305c-4e26-bdd8-813b0d94b93c,3,2/5/2000,2/16/2000,,92360be3-a39a-4142-aa0f-ae0ad41ec2cf,3,2/5/2000,6/3/2014,6/3/2014,Total rows: 19

f748122f-4123-48ee-91f0-df2ea981a693,3,12/1/2005,12/1/2005,,e5ad96fd-fa49-4125-815f-30f90c82dd68,3,12/1/2005,6/3/2014,6/3/2014,Total rows: 19

fc240c14-8b67-4a14-a7c0-86da9ca2ef18,3,2/5/2000,2/16/2000,,295b5b30-c84d-4612-b023-63ca17fa81db,3,2/5/2000,6/3/2014,6/3/2014,Total rows: 19

aaf2e4a6-0bdb-44af-80b8-c217c1f1c905,3,10/6/2009,10/6/2009,,c38b6d08-fb71-48e0-8b2f-f3e3b80bd30f,3,10/6/2009,5/5/2014,5/5/2014,Total rows: 19

**Comment by andershessellund** [comment]
When switch to using DAR 0.9 as data source for adresses instead of BBR, there will no longer be any adresses without an access adress. The change is scheduled to happen the 11. may.
