### ISSUE TITLE
Autocomplete af "Lærkevej" giver ikke liste af adgangsadresser

### ISSUE THREAD

**Issue by jrftrifork** [DanmarksAdresser/Dawa#357]
Hvis man på http://autocomplete.aws.dk taster "Lærkevej" i feltet "Adresse" under "Autocomplete af adresse", får man en liste af vejnavne med bla. "Lærkevej" og "Lærkevejen" som muligheder.
Hvis man trykker på "Lærkevejen" får man en liste med adgangsadresser på "Lærkevejen" i forskellige postnumre.
Hvis man gør det samme med "Lærkevej", får man bare vejnavnelisten. 

Hypotesen er, at query'et for adgangsadresser hvor vejnavn er Lærkevej returnerer så mange hits, at det kører langsomt, og at det ødelægger et eller andet timing i autocomplete-komponent

**Comment by andershessellund** [comment]
Årsagen er, at et tryk p.t. blot udfylder tekstfeltet med "lærkevej", hvilket stadig matcher flere veje. Derfor query'er vi aldrig på adgangsadresserne.

Man kan godt lave det sådan, at den altid fortsætter til adgangsadresser, når man vælger et vejnavn i listen, men der vil stadig blive returneret adgangsadresser for andre veje der ikke matcher "lærkevej" præcist. Det vil de fleste brugere nok alligevel opfatte mere intuitivt end den nuværende opførsel.

**Comment by finnjordal** [comment]
Kunn man ikke når man fortsætter med adgangsadresser kræve at vejnavnet er det valgte ved at anvende /adgangsadresser/autocomplete?vejnavn=Lærkevej&q=...

**Comment by andershessellund** [comment]
Det kunne man godt. Men problemet er at brugeren ikke nødvendigvis kender
den korrekte stavemåde på vejen. Hvis han vælger forkert, og vi benytter
vejnavn parameteren, så vil han ikke kunne vælge den korrekte adresse
efterfølgende. Det bliver også noget mere komplekst (e.g. håndtering af
backspace knappen).

**Comment by andershessellund** [comment]
Flytter den tilbage til backlog, da den ikke er afklaret helt endnu.
