### ISSUE TITLE
Skal autocomplete af adresser præsenterer vejnavne uden adresser?

### ISSUE THREAD

**Issue by finnjordal** [DanmarksAdresser/Dawa#359]
https://twitter.com/zgail/status/560449814723579904

Måske kunne vejnavne uden adresser markeres i dropdown-listen.
Udeladelse af vejnavne uden adresser i dropdown-listen kan skabe forvirring

**Comment by andershessellund** [comment]
Det ville være hjælpsomt, hvis autocomplete-komponenten fortæller brugeren hvad det er for en vej der matcher, samt at der ikke er nogen adresser på vejen.
