### ISSUE TITLE
Forslag til vejnavne

### ISSUE THREAD

**Issue by hoerup** [DanmarksAdresser/Dawa#372]
Det kunne være fedtom DAWA også kunne komme med forslag til vejnavne hvis man har et vejnavn som er tastet forkert.

Feks. 
Input: Kålagevej&postnr=2300
Output: "Kålagervej"
Input: Snaregdae&postnr=1205
Output: Snaregade

**Comment by andershessellund** [comment]
Vi har vurderet dette forslag, og vi har tænkt os at implementere det.

Løsningen vil blive baseret på den såkaldte levenshtein edit-distance. Dvs. de forslag man får tilbage vil være de vejnavne som kræver færrest edits (indsættelse, sletning eller ændring af en karakter). Sammenligningen vil ske på den rå tekststreng, men vil dog være case insensitiv.

Løsningen vil returnere flere resultater, f.eks. de 10 bedste matches med den bedst matchende først. Desuden vil vi returnere den beregnede edit-afstand for hvert match. Det vil blive muligt at filtrere på postnummer og kommunekode.

Vi kan endnu ikke give nogen tidshorisont for hvornår denne feature er implementeret. BBR er p.t. i gang med nogle ændringer, som ændringer i de API'er vi har til rådighed, og det har højeste prioritet at vi sikrer at vi fortsat kan modtage adresseopdateringer.

**Comment by andershessellund** [comment]
I næste release vil søgefunktionaliteten være forbedret, så det er muligt at udføre såkaldt fuzzy søgning. Det vil sige, at hvis der ikke er nogle hits på den almindelige søgning, så får man en liste med forslag, som matcher bedst muligt, men ikke nødvendigvis helt nøjagtigt.
