### ISSUE TITLE
Kildeskattepligtig

### ISSUE THREAD

**Issue by mawolf** [DanmarksAdresser/Dawa#376]
Følgende adresse meldes som ikke-eksisterende:
Postnummer: 9999
Vejnavn: Kildeskattepligtig

Se http://dawa.aws.dk/vejnavne?postnr=9999&q=Kildeskattepligtig

Den findes dog på:
http://geo.oiorest.dk/kommuner/0011/vejnavne/0071.html

Den bruges til ambassader og til folk der ikke har en rigtigt adresse, men den _er_ en adresse :-).

**Comment by finnjordal** [comment]
Hej Martin

DAWA  indeholder udelukkende adresser, som betegner fysiske lokationer, som f.eks. boliger, legepladser, grunde, tekniske anlæg osv. DAWS rummer ikke de fiktive adresser, som CPR anvender.

Mvh.
Finn

**Comment by mawolf** [comment]
Hej Finn,

Tak for dit svar! Det er en skam - det giver os nogle problemer i forbindelse med validering af adresser, som personer faktisk er registrerede med og derfor egentlig korrekte for os.

Bedste hilsner,
Martin

**Comment by olejorgensen** [comment]
Jeg støder på vejnavnet når jeg importerer vejstykker fra http://dawa.aws.dk/vejstykker?format=geojson
Der er netop et resultat på vejstykker http://dawa.aws.dk/vejstykker?q=Kildeskattepligtig

**Comment by finnjordal** [comment]
Det er en fejl at vi importere vejstykker uden kommuneangivelse. Det vil
blive rettet.
Indtil da kan du se bort fra vejstykker uden kommuneangivelse.


2017-05-01 16:01 GMT+02:00 Ole Jørgensen <notifications@github.com>:
