### ISSUE TITLE
GeoServeren præsenterer nogle adresser dobbelt

### ISSUE THREAD

**Issue by finnjordal** [DanmarksAdresser/Dawa#405]
Eksempel: Følgende adresse er enkelt i DAWA, men dobbelt i geoserveren: Anemonen 501, 2635 Ishøj. Det er en havekoloni, hvor alle adresser er dobbelt.
Kan der være noget i SQL, som definerer viewet?

**Comment by andershessellund** [comment]
Det er en datafejl. Kommunen har oprettet dobbelt-adresser i stedet for at ændre den eksisterende
