### ISSUE TITLE
Replikering på adresser indeholder ikke KVHX

### ISSUE THREAD

**Issue by raunsbaekdk** [DanmarksAdresser/Dawa#407]
Hej

```
{
  "id": "000872d7-d993-4942-97db-7ef7f3a4d9e1",
  "status": 1,
  "oprettet": "2014-05-05T19:07:48.577",
  "ændret": "2014-05-05T19:07:48.577",
  "ikrafttrædelsesdato": "2014-05-05T19:07:48.577",
  "etage": null,
  "dør": null,
  "adgangsadresseid": "0a3f507b-b664-32b8-e044-0003ba298018",
  "kilde": 11,
  "esdhreference": null,
  "journalnummer": null
}
```

Dette er et udsnit af /replikering/adresser, og der mangler KVHX, adressebetegnelse samt href (ikke så vigtig).

**Comment by andershessellund** [comment]
Felterne KVHX, adressebetegnelse og href kan beregnes ud fra de eksisterende felter. Replikeringen er teknisk set implementeret sådan, at den udstiller en normaliseret datamodel. Derfor vil adressebetegnelse, KVHX og href ikke blive udstillet på replikerings-API'et.
