### ISSUE TITLE
Tilføj newline json format

### ISSUE THREAD

**Issue by AndreasMadsen** [DanmarksAdresser/Dawa#418]
På sider så som http://dawa.aws.dk/replikering/adgangsadresser er det ikke pratisk at have alt data i hukommelsen. Man må derfor lave en stream parser. Der findes moduler som `JSONstream` i node.js til at gøre det, men det er ikke godt vedligeholdt og en unødig kompliceret måde at gøre det på.

En bedre måde vil være at bruge [Line Delimited JSON](https://en.wikipedia.org/wiki/Line_Delimited_JSON), hvilket er en langt mere udbredt standard.

Dette bør nemt kunne integreres i jeres nuværende setup, ved at introducere en ny `format=` mulighed, fx `&format=ldjson`.

**Comment by andershessellund** [comment]
Hej Andreas,

Det lyder som en god idé at tilbyde Line Delimited JSON.

**Comment by AndreasMadsen** [comment]
Super

**Comment by AndreasMadsen** [comment]
@andershessellund Hvad er udsigterne til det her? Jeg kunne godt selv implementere det, men efter som jeres interne database ikke er tilgængelig, vil det være ret svært for mig at teste.

**Comment by andershessellund** [comment]
Hej Andreas,

Jeg kan ikke give dig et tidspunkt for hvornår vi implementerer dette, men vi vil være meget glade hvis du vil bidrage.

Jeg har udvidet udviklerdokumentationen med information om hvordan du afvikler test-suiten, herunder hvordan man indlæser en test-database. Der er kun nogle få tusind adresser, men det bør være tilstrækkeligt til at du kan teste denne funktionalitet. Ellers må jeg skaffe en kopi af vores produktions-database til dig.

Udviklerdokumentationen er her:

https://github.com/DanmarksAdresser/Dawa/blob/master/doc/Udviklerdokumentation.md

Det er væsentligt for os, at løsningen kan komme til at fungere både med default formatet (json) samt med geojson formatet. Jeg tænker derfor umiddelbart, at vi tilføjer en ny boolean parameter, ldjson, som kan angives sammen med format=json og format=geojson. Du behøver dog ikke implementere geojson udgaven i første omgang. Hvis du har andre ideer er vi lydhøre.

**Comment by AndreasMadsen** [comment]
Tænkte faktisk på at implementere `format=ld-json` og `format-ld-geojson`. At bruge `?ldjson=&format=json` giver det problem at fx `jdjson=&format=csv` ikke er veldefineret. Men hvis det ikke er et problem, er `?ldjson=` sikkert det nemmeste.

PS: [linje 58 i udvikler dokumentation](https://github.com/DanmarksAdresser/Dawa/blame/master/doc/Udviklerdokumentation.md#L58) ser lidt sjov ud, mener du `pgConnectionUrl==postgres://<user>:<password>@localhost/dawaempty node psql/setup-db.js`.

**Comment by andershessellund** [comment]
Yep, jeg har fikset dokumentationen.

Hvis man anvender ldjson parameteren sammen med format=csv eller sammen med callback-parameteren (JSONP), så skal det gerne give en fejl 400 tilbage.
