### ISSUE TITLE
Funktionalitet til beregning af midten af DAGI flade. Herunder Kommune. 

### ISSUE THREAD

**Issue by finnjordal** [DanmarksAdresser/Dawa#430]
https://twitter.com/DuGi/status/648391604101861376

**Comment by hoerup** [comment]
Ud over centrum af fladen kunne det måske være en idé med max(latitude), min(latitude), max(longitude), min(longitude) - hvis man ikke behøver den fulde outline men bare skal bruge en ca boundary for fladen
