### ISSUE TITLE
Vejnavn, som ikke findes via vejnavne og vejstykker, dukker op i autocomplete

### ISSUE THREAD

**Issue by finnjordal** [DanmarksAdresser/Dawa#432]
Eksempel: Keld Petersens Plads, som er slettet d. 24/9

**Comment by andershessellund** [comment]
Den vej der findes i autocomplete er Kjeld Petersens Plads (altså med Kj). Den findes p.g.a. fuzzy søgning, og den findes også på opslags-API'et:

http://dawa.aws.dk/vejnavne?q=Kjeld%20petersens%20Plads

**Comment by andershessellund** [comment]
Jeg kan ikke konstatere nogen fejl.
