### ISSUE TITLE
Zone queryparameteren fejler

### ISSUE THREAD

**Issue by finnjordal** [DanmarksAdresser/Dawa#440]
Hvis man slår en enkelt adresse op i Dragørkommune i json format, som man ved ligger i landzone, får man den korrekte zoneangivelse – nemlig landzone

http://dawa.aws.dk/adgangsadresser?vejnavn=Kalvebodvej&husnr=166&postnr=2791&Drag%C3%B8r&cache=no-cache

Hvis man forsøger at anvende zonekoden som queryparameter, får man ikke noget resultat retur. Uanset hvilken zonekode man anvender

http://dawa.aws.dk/adgangsadresser?vejnavn=Kalvebodvej&husnr=166&postnr=2791&Drag%C3%B8r&cache=no-cache&zonekode=1|2|3

**Comment by andershessellund** [comment]
Hej Finn,

Det skyldes formentlig den fejl jeg omtalte - at landzone mange steder ikke
er eksplicit registreret på zonekortet.

Mvh
Anders

Den mandag den 30. november 2015 skrev finnjordal <notifications@github.com

**Comment by finnjordal** [comment]
Hej Anders

Det ved jeg godt - tog den bare med så vi huskede den.

Hilsen
Finn
