### ISSUE TITLE
Max antal samtidige requests overskredet (429) resulterer i en html side - bør det ikke være vor standard json fejlbesked?

### ISSUE THREAD

**Issue by finnjordal** [DanmarksAdresser/Dawa#441]

**Comment by mast4461** [comment]
Hvad er grænsen for "max antal samtidige requests"? Eller, hvor kan mand finde information om det?

Tak!

/Martin Stålberg

**Comment by finnjordal** [comment]
Hej Martin

Dokumentationen, som kommer med i næste release, er følgende:

Maksimalt antal samtidige requests
Der er en grænse på hvor mange samtidige requests til DAWA, der må foretages fra en enkel IP adresse. Grænsen er på 10 samtidige requests. Baggrunden for at sætte denne grænse er, at forhindre en enkelt anvenders brug af DAWA påvirker andre anvendere. F.eks. i form af lange svartider eller fejl i kald af servicen.

Hvis grænsen på 10 samtidige requests overskrides returneres responses med HTTP statuskoden 429 Too Many Requests.

Mvh
Finn

**Comment by mast4461** [comment]
Magne tak!
