### ISSUE TITLE
Adresse bliver udstillet uden vejnavn

### ISSUE THREAD

**Issue by finnjordal** [DanmarksAdresser/Dawa#444]
http://dawa.aws.dk/adresser?id=0a3f50b1-ece6-32b8-e044-0003ba298018 bliver udstillet uden vejnavn, men med vejkode

**Comment by andershessellund** [comment]
Jeg har kigget på sagen, og det er ikke i vores system problemet ligger. Vi modtager ganske enkelt vejnavnet fra DAR med vejnavn tom streng. Vi burde dog benytte tom streng i stedet for null i visningen.

Der er flere mulige årsager til fejlen:
1) Fejl i DAR
2) Fejl i CPR
3) Brugerfejl - nogen har ved en fejl fjernet vejnavnet (som oprindeligt var halmvænget) i CPR.
4) Brugerfejl - vejen findes ikke længere, men man har glemt at slette adressen.

**Comment by finnjordal** [comment]
Vejstykket er slettet d, 16/12-2015 http://cprvej.danmarksadresser.dk/(S(b3om2clarjxjutc2qckbtgj2))/SlettedeVeje.aspx

**Comment by andershessellund** [comment]
I så fald, så er der to fejl som ikke vedrører vores system:
1) Vejen er blevet slettet uden at adressen er blevet nedlagt. Det er vel kommunen der skal fikse dette og få nedlagt adressen.
2) Vejnavn-udtrækket fra DAR har ikke et ophoerttimestamp for denne vej. Det kan vi godt selv håndtere, men det er stadig lidt mærkeligt at vi får et vejstykke hvor vejnavnet er slettet, i stedet for at der blot er sat et ophoerttimestamp. 

Derudover bør vi filtrere adresser uden vejnavn fra på opslags-API'et. Vi filtrerer aktuelt kun de fra som ikke har et postnr.
