### ISSUE TITLE
Undgå æøå i feltnavne

### ISSUE THREAD

**Issue by hoerup** [DanmarksAdresser/Dawa#445]
F.eks. adgangsadresse har et felt under  adgangspunkt der hedder "nøjagtighed" - her ville en navngivning udelukkende med a-z være at foretrække (f.eks. nojagtighed eller noejagtighed)

**Comment by finnjordal** [comment]
Hvorfor? Har du problemer med æøå i feltnavne?

**Comment by andershessellund** [comment]
Vi kan ikke ændre i feltnavnene, da det ikke vil være en bagudkompatibel ændring. Det er heller ikke min opfattelse at der er nogen almindeligt anvendte programmeringssprog hvor det er et problem at håndtere æ, ø og å.
