### ISSUE TITLE
Forespørgsel på HTTPS giver 'href' med HTTP

### ISSUE THREAD

**Issue by raunsbaekdk** [DanmarksAdresser/Dawa#450]
Når man henter via HTTPS, så kommer alle 'href' med HTTP. Her bør den kigge på om man forespørger via HTTPS og selvfølgelig også vise href's med HTTPS.

Hent f.eks.: https://dawa.aws.dk/adresser/autocomplete?q=Kongens%20Nytorv%201%201050

Så får du dette tilbage:

```
{
	tekst: "Kongens Nytorv 1, 1., 1050 København K",
	adresse: {
		id: "20195b5e-51e7-48e0-a4c1-7870b6e8dae9",
		href: "http://dawa.aws.dk/adresser/20195b5e-51e7-48e0-a4c1-7870b6e8dae9",
		vejnavn: "Kongens Nytorv",
		husnr: "1",
		etage: "1",
		dør: null,
		supplerendebynavn: null,
		postnr: "1050",
		postnrnavn: "København K",
		stormodtagerpostnr: null,
		stormodtagerpostnrnavn: null
	}
}
```

Her er href: http://dawa.aws.dk/adresser/20195b5e-51e7-48e0-a4c1-7870b6e8dae9

Det giver nogle frygtelige 'Mixed Content'-fejl, når man forsøger at følge href'en.

Mixed Content: The page at 'https://SUBDOMAIN.herokuapp.com/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://dawa.aws.dk/adresser/20195b5e-51e7-48e0-a4c1-7870b6e8dae9'. This request has been blocked; the content must be served over HTTPS.

**Comment by andershessellund** [comment]
Dette har vi nu mulighed for at implementere, da CloudFront nu kan medsende en header CloudFront-Forwarded-Proto og supportere forskellige cachede kopier baseret på denne header.

Jeg synes klart vi burde gøre dette.

**Comment by finnjordal** [comment]
Helt enig. Vi har haft problemstillingen oppe før, men den gang var det ikke muligt.

**Comment by andershessellund** [comment]
Dette er nu fikset.
