### ISSUE TITLE
Autocomplete giver forkerte adresse-ID'er for partielle adresser.

### ISSUE THREAD

**Issue by fredefox** [DanmarksAdresser/Dawa#453]
Hvis jeg kalder:

    http://dawa.aws.dk/autocomplete?q=Sverigesvej+10

Får jeg følgende svar (noget data er udeladt):

    [
    {
      "forslagstekst": "Sverigesvej 10, 4180 Sorø",
      ...
      "data": {
        "id": "0a3f5084-8ce8-32b8-e044-0003ba298018",
        ....
      }
    },
    ...
    ]

Hvis jeg derimod kalder

    http://dawa.aws.dk/autocomplete?q=Sverigesvej+10%2C+%2C+4180+Sor%C3%B8

Får jeg følgende svar tilbage (noget data er udeladt):

    [
    {
      "forslagstekst": "Sverigesvej 10, 4180 Sorø",
      ...
      "data": {
        "id": "0a3f50ae-ec1f-32b8-e044-0003ba298018",
        ...
      }
    }
    ]

Der er altså nu ét resultat, svarende til den samme adresse, men læg her mærke
til at id'et ikke er det samme.

Bemærk at det første ID ikke findes hvis jeg slår det op via:

    http://dawa.aws.dk/adresser/0a3f5084-8ce8-32b8-e044-0003ba298018

Hvorimod det andet faktisk eksisterer:

    http://dawa.aws.dk/adresser/0a3f50ae-ec1f-32b8-e044-0003ba298018

**Comment by andershessellund** [comment]
/autocomplete er en kombineret autocomplete, som både søger i vejnavne, adgangsadresser og adresser. Det fremgår af "type" feltet hvad det er man modtager.

I den første søgning er det adgangsadresser du modtager. Adresser modtages kun, hvis der er indtastet tilstrækkeligt mange oplysninger til at fastslå adgangsadressen entydigt. Derfor modtager du også en adgangsadresse id, og ikke en adresse id.

Hvis du kun vil modtage adresser, så skal du benytte /adresser/autocomplete?q=<query>, eller du skal benytte /autocomplete sammen med query parameteren startfra=adresse .

**Comment by fredefox** [comment]
Perfekt! Tak fordi du opklarede det for mig @andershessellund.
