### ISSUE TITLE
Requests med HEAD beregnes på serveren

### ISSUE THREAD

**Issue by LordMike** [DanmarksAdresser/Dawa#455]
Hej,

Når man laver en HEAD (fremfor en GET) tager requestene tid at udføre, så meget at det tyder på at data bliver hentet fra databaserne og processeret (dog ikke sendt til klienten).

Som eksempel tager `http://dawa.aws.dk/adresser?format=geojson&noformat`:
* GET m/ GZIP: 20 minutter
* HEAD: 1 minut og 30 sekunder

Dybest set skal der vel bare returneres en statisk, blank side.

Mvh.

**Comment by andershessellund** [comment]
Tak for fejlrapporten. Vi fremover returnere 405 Method not allowed på HEAD requests. Hvis nogen ønsker at benytte HEAD fremover, vil vi måske indføre den igen.

**Comment by LordMike** [comment]
I bør give samme retur for POST, PATCH og alt andet - dybest set kun tillade GET.

**Comment by andershessellund** [comment]
POST, PATCH osv. afvises heldigvis automatisk. Det er kun for HEAD requests at vores HTTP-framework har synes det var en god idé at håndtere det som en GET-request hvor body smides væk.
