### ISSUE TITLE
Fejl i GeoJSON output - ikke standardscompliant

### ISSUE THREAD

**Issue by LordMike** [DanmarksAdresser/Dawa#456]
Hej,

Jeg rodede lidt med GeoJSON formatet og prøvede at læse det med GeoJSON.Net, som så smed en exception omkring en manglende `geometry`. Jeg fandt så efterfølgende 136 `adresse`r med manglende geometry-felt.

Et eksempel er denne: http://dawa.aws.dk/adresser/13f92346-3b79-4800-adc8-9cba74f7250c?format=geojson

I standarden for GeoJSON (http://geojson.org/geojson-spec.html#feature-objects) står der at "A feature object must have a member with the name "geometry". The value of the geometry member is a geometry object as defined above or a JSON null value."

Kan I ændre det således at i returnerer `"geometry": null` når der ikke er et koordinat?

Jeg har testet og bekræftet at ved indsættelse af `null` så parses features'ne fint i GeoJSON.Net.

Mvh.
Michael

**Comment by andershessellund** [comment]
Hej Michael,

Tak for fejlrapporten. Jeg har fikset dette, så fejlen er rettet næste gang vi laver i et release. Det bliver i denne uge.
