### ISSUE TITLE
Søgning på kommuner ud fra regions kode

### ISSUE THREAD

**Issue by hoerup** [DanmarksAdresser/Dawa#457]
Det er pt ikke muligt at søge kommuner ud fra regionskode.

F.eks. http://dawa.aws.dk/kommuner?region=1081

**Comment by finnjordal** [comment]
Du kan se hvilke parametre, der kan anvendes i forhold til kommunesøgning på http://dawa.aws.dk/listerdok#kommunesoegning. Det er ganske rigtigt, at du ikke kan søge på regionskoden. Har du behov for at kunne fremsøge kommuner ud fra regionskoden?
