### ISSUE TITLE
Foranstillede nuller i dørnumre

### ISSUE THREAD

**Issue by bjarkebm** [DanmarksAdresser/Dawa#460]
Hej Dawa,

Hvordan håndteres foranstillede nuller i dørnumre?
Pt. findes der 2643 enhedsadresser med et eller flere foranstillede nuller i dør.

Jeg skriver fordi jeg er stødt på enhedsadresserne 
"12f5b6d4-6f2c-4eb9-b5fc-dcd04eea003f" og "11900a1d-1786-435f-af13-277da0e21222" som virker til at være identiske adresser, blot med den forskel at den ene har en dør der hedder "2" og den anden har en dør der hedder "0002".

Er det en fejl i data? Eller kan man forestille sig tilfælde hvor det er to forskellige adresser?

Lidt mere data:
"12f5b6d4-6f2c-4eb9-b5fc-dcd04eea003f"
"adressebetegnelse": "Stormgade 9, st. 2, 9000 Aalborg"
"kvhx": "08517925___9_st___2",

"11900a1d-1786-435f-af13-277da0e21222"
"adressebetegnelse": "Stormgade 9, st. 0002, 9000 Aalborg",
"kvhx": "08517925___9_st0002",

**Comment by finnjordal** [comment]
Hej Bjarke

Umiddelbart ser det ud til at være identiske adresser, men set ud fra et DAWA synspunkt, kan vi ikke afgøre hvorvidt de er identiske. Det kan kun den kommunale adressemyndighed i Aalborg kommune, som du kan henvende dig til for at få det afklaret.

Mvh.
Finn

**Comment by bjarkebm** [comment]
OK, tak for svar :-)
