### ISSUE TITLE
Sortering af adresser

### ISSUE THREAD

**Issue by cfischer00** [DanmarksAdresser/Dawa#464]
Det er ikke altid at adgangsadresser sorteres på en måde, som man forventer. Hvis man f.eks. kalder:
https://dawa.aws.dk/adgangsadresser/autocomplete?q=buskmosevej%202&type=adgangsadresse&kommunekode=540

Kommer "Buskmosevej 2, Rinkenæs, 6300 Gråsten" først ind på 4. pladsen. Foran den kommer et nummer 22, 24 og 22C.

Det er desværre ikke muligt at sortere i klienten på en fornuftig måde - det er ikke muligt at beslutte hvor mange adresser man skal returnere for at kunne sortere korrekt.

**Comment by finnjordal** [comment]
Jeg vil anbefale, at du bruger den generelle autocomplete funktionalitet:
http://dawa.aws.dk/autocomplete?type=adgangsadresse&kommunekode=540&q=l%C3%A6rkevej%202

**Comment by cfischer00** [comment]
Jeg synes ikke jeg kan få det til at virke. Hvis jeg skyder med:
http://dawa.aws.dk/autocomplete?type=adgangsadresse&kommunekode=540&q=buskmosevej%202
mangler 22, 24 og 22C.

Hvis jeg forsøger med * efter husnummer:
http://dawa.aws.dk/autocomplete?type=adgangsadresse&kommunekode=540&q=buskmosevej%202*
får jeg præcis samme sortering som den specifikke autocomplete.

Gør jeg noget galt?

**Comment by finnjordal** [comment]
Baggrunden for ikke at returnere 22, 24 og 22C er, at mange kombinationer af vejnavne og husnumre optræder mange gange som f.eks. Lærkevej 2. I disse tilfælde ønsker vi udelukkende at præsentere brugeren for pågældende kombination af vejnaven og husnummer - og ikke forurene søgeresultatet med andre husnumre.

**Comment by cfischer00** [comment]
Alle 2'ere skal selvfølgelig øverst og derefter de andre husnumre, der matcher med 2*. Jeg vil tro at det kan klares med en anden sorteringsalgoritme i den bagvedliggende service:

- Først alle adresser hvor husnummeret passer eksakt med det indtastede
- Dernæst alle adresser hvor husnummeret har efterfølgende cifre (eller bogstav). Disse sorteres primært numerisk efter husnummer, sekundært efter bogstav.

Udfordringen for slutbrugeren er at hvis han leder efter f.eks. "Buskmosevej 24", dukker den ikke op i listen når han skriver "Buskmosevej 2" - det forventer han i en drop-down box.

**Comment by finnjordal** [comment]
Vi bruger Postgres' rankingfunktionalitet til at sortere søgeresultaterne. Det er ikke helt lige til at lave en anden sortering efterfølgende, som vi er sikker på opfylder brugerens behov.
Men vi vil forsøge.

**Comment by cfischer00** [comment]
Hvis jeg kan hjælpe må du endelig sige til. Send evt. link til den SQL, som laver ranking, så kan jeg give det et skud.
