### ISSUE TITLE
Lade Autocomplete respektere polygon input parameter

### ISSUE THREAD

**Issue by klavspc** [DanmarksAdresser/Dawa#521]
Hvordan vil man tilbyde brugere en adressesøgning i et område, som ikke er defineret af postnummer eller kommunenummer?

De øvrige adressesøgninger respekterer _polygon_, men autocomplete gør ikke.

**Comment by andershessellund** [comment]
Der er forskellige tekniske årsager til, at autocomplete sammen med polygonsøgninger ikke vil fungere specielt godt.

Et problem er, at vi vil få svært ved at sikre en god query-tid, alt afhængigt af hvordan polygonet ser ud.

**Comment by andershessellund** [comment]
Et andet problem er, at autocomplete søger progressivt gennem vejnavne, adgangsadresser og adresser. Men ved søgning i vejnavne er det vanskeligt at afgøre, om vejnavnet ligger indenfor polygonet eller ej.

**Comment by andershessellund** [comment]
Du kan dog godt søge direkte i adgangsadresser eller adresser og kombinere q- og polygonparametre - men vær forberedt på, at det muligvis ikke vil performe så godt.

http://dawa.aws.dk/adressedok#adresseautocomplete

**Comment by klavspc** [comment]
@andershessellund:

Tak for dine svar.

Der kan være mange eksempler på at polygonafgrænsning i autocomplete vil være nyttig. Konkret ønsker CPH lufthavn en autocomplete-agtig søgning på de adresser, som er interessante for dem (Defineret som buffer omkring deres areal) Denne søgning kan jeg ikke give dem med vores standardløsning som baserer sig på autocomplete i tandem med de øvrige søgninger.

Jeg har følgende kommenterer til dine tidligere kommentarer:
> Et andet problem er, at autocomplete søger progressivt gennem vejnavne, adgangsadresser og adresser. Men ved søgning i vejnavne er det vanskeligt at afgøre, om vejnavnet ligger indenfor polygonet eller ej.  

Hvis der på vejen findes adresser inden for polygonet bør vejen vises i autocomplete. Hvis efterfølgende progressive søgninger også respekterer polygonet vil brugeren have en smidig oplevelse.

> Der er forskellige tekniske årsager til, at autocomplete sammen med polygonsøgninger ikke vil fungere specielt godt.

Selvfølgelig er det underliggende datagrundlag og algoritmen optimeret til denne type søgning. Alligevel mener jeg at autocomplete bør opdateres så den bringes mere i overensstemmelse med de øvrige søgninger. Se i øvrigt #532
