### ISSUE TITLE
Autocomplete returnerer veje uden adresser

### ISSUE THREAD

**Issue by klavspc** [DanmarksAdresser/Dawa#531]
Eksempel:
På http://dawa.aws.dk under titlen Autocomplete af adgangsadresse søges på _Christian Sørensens_. _Christian Sørensens Allé_ (Hvidovre) vises nu, men når den vælges er den forsvundet.

Det skyldes formodentlig at der har været et tidligt hit på vejnavn uden at det er konstateret, at der ikke er nogen på adresser.

Løsningen kunne være at udelade veje uden adresser fra det datagrundlag, der anvendes i autocomplete.

**Comment by Ellebjerg** [comment]
I stedet for at udelade veje uden adresser fra autocomplete, virker det mere relevant at inkludere veje uden adresser i resultatet. Kommuner og forsyningsselskaber har ofte brug for at få vist veje, også uden angivelse af et specifikt husnummer, og det kan også være yderst relevant for vejvisningssystemer m.m.
Så når fx adressesøg i Septimas S4 kan vise hele vejen, inden der tastes husnummer, burde den også kunne vise hele vejen, hvis der ikke findes et husnummer.

**Comment by klavspc** [comment]
Hvordan kan det være, at dette issue er afvist? Det virker da umiddelbart som en fejl, at autocomplete i en adressesøgning returnerer veje, der ikke har adresser. Det betyder, at autocomplete leder brugeren ned ad en blindgyde. Her er et andet eksempel med _Fuldbrovej_.

![#531_1](https://user-images.githubusercontent.com/3736091/58160104-131e7f00-7c7e-11e9-97ef-09576c7cbac5.png)

![#531_2](https://user-images.githubusercontent.com/3736091/58160109-1580d900-7c7e-11e9-9506-6a5aabeabdd1.png)

**Comment by andershessellund** [comment]
Hej Klavs,

Adresse-autocomplete er lavet ud fra en formodning om, at folk kender den adresse de er ved at indtaste. Derfor ser vi det ikke som noget stort problem at der fremgår vejnavne, som ikke har nogen adresser. Vi formoder det vil være meget sjældent, at en bruger forsøger at indtaste en adresse, som ikke findes.

Det ville være hensigtsmæssigt, hvis vi kunne give lidt bedre feedback til brugeren, hvis der forsøges at indtaste en adresse, som ikke findes. Men det er ikke et helt simpelt problem at løse. Hvis vi undlader at vise vejnavnet i autocomplete fordi der ikke er nogen adresser, så vil det også være mindst lige så forvirrende for brugeren. Der kan også være nogle vejstykker hvor der er adresser, og nogle hvor der ikke er, og vi kan jo ikke på det tidspunkt vide, om brugeren forsøger at indtaste en adresse på det vejstykke der ikke er nogen, eller på det vejstykke hvor der er.

Du skriver i det linkede issue, at "Der er en fejl i dawa således at veje ikke kan findes, hvis de ikke har nogen adresser." Kan du uddybe hvad det er for en fejl i oplever? Så vidt jeg kan konstatere kan man godt fremsøge vejstykker, som ikke har nogen adresser. Problemet er måske, at de ikke har nogle tilknyttede postnumre?

**Comment by andershessellund** [comment]
Jeg har oprettet https://github.com/DanmarksAdresser/Dawa/issues/735 vedrørende vejstykker uden adresser, som ikke har nogle postnumre.

**Comment by andershessellund** [comment]
Jeg har oprettet #740, som måske vil have jeres interesse @klavspc . I er velkomne til at komme med jeres input.
