### ISSUE TITLE
Address Cleaner Issue

### ISSUE THREAD

**Issue by benjamin-wss** [DanmarksAdresser/Dawa#537]
Hello Devs,

We were working on some stuff that uses the DAWA as a Geocoder for Danish addresses. 

We do not get the return payload that we expect from DAWA when we enter the following address:

`Ravnsnæsvej 36, 3460 BIRKERØD`

It would only get us the Geocode (Latitude,Longitude) if we were to enter either:

`Ravnsnæsvej 36A, 3460 BIRKERØD`
`Ravnsnæsvej 36B, 3460 BIRKERØD`

What we did was that we used the address cleaner via this GET request:

`https://dawa.aws.dk/datavask/adresser?betegnelse=`

We then rely on the the `href` field from the `resultater.aktueladresse` array field to get what we want.

While we managed to recover from this relatively quickly, we would like to know if there is a better way to deal with this or if this fix is already in the works.

**Comment by finnjordal** [comment]
Hi Benjamin
"Ravnsnæsvej 36, 3460 Birkerød" is a abolish address, and are replaced by "Ravnsnæsvej 36A, 3460 Birkerød" and "Ravnsnæsvej 36B, 3460 Birkerød". Status = 2 indicates that the address is abolish. The address no longer exists and can not be accessed through the API.

**Comment by benjamin-wss** [comment]
I see, however, shouldn't the address cleaner then put it to the nearest address then? The array returned should have given us corrections, no?

**Comment by finnjordal** [comment]
"Ravnsnæsvej 36, 3460 BIRKERØD" is an exact match, so it would be a bad idea to return another address. Normally, when an address is split up in two, one of the new address (34A or 34B) would take ID from the old one (36), and you would get the new address in the address cleaning.

**Comment by benjamin-wss** [comment]
Very well. I see your point. 

We will work around this.

Thanks for your feedback.

Great work with the API btw.
