### ISSUE TITLE
OIS udeståender

### ISSUE THREAD

**Issue by andershessellund** [DanmarksAdresser/Dawa#551]
1) Rækkefølge
ENHEDER
BYGNINGER
TEKNISKEANLAEG
EJERSKABER
GRUNDE
MATRIKELREFERENCER
OPGANGE
ETAGER
BYGNINGSPUNKTER
KOMMUNER

2) OIS grunde søgning ændres til  Grunde søgning

3) GeoJSON fejl

4) Bygningspunkt har ikke noget eksempel

5) Matrikelreferencer mangler et eksempel

**Comment by finnjordal** [comment]
Bygningspunkt har ikke noget eksempel.

**Comment by finnjordal** [comment]
Ser ikke ud til at være lavet
