### ISSUE TITLE
Dokumentation af "Maksimalt antal samtidige requests" opdateres

### ISSUE THREAD

**Issue by finnjordal** [DanmarksAdresser/Dawa#606]
Maksimalt antal samtidige requests
Der er en grænse på hvor mange samtidige requests til DAWA, der må foretages fra en enkel IP adresse. Grænsen er på 10 samtidige requests. Baggrunden for at sætte denne grænse er, at forhindre en enkelt anvenders brug af DAWA påvirker andre anvendere. F.eks. i form af lange svartider eller fejl i kald af servicen.

Hvis grænsen på 10 samtidige requests overskrides returneres responses med HTTP statuskoden 429 Too Many Requests.

**Comment by andershessellund** [comment]
Tilføjes til FAQ
