### ISSUE TITLE
Adresses may disappear as time passes

### ISSUE THREAD

**Issue by danchr** [DanmarksAdresser/Dawa#626]
I also reported this on the [digitaliser.dk forums](https://www.digitaliser.dk/forum/4193277).

I am working on an application — [magenta-aps/mora](/magenta-aps/mora) — where we save addresses to a database. Our general assumption, so far, was that could resolve addresses using DAWA, save the URL or UUID, and then perform a request to obtain the actual address data when rendering the address. In production, the application would not be exposed to the public internet, and we don't expect terribly significant load in practice; hence, avoiding caching felt like a good shortcut to take. (Please let us know if you would rather avoid such usage.)

Unfortunately, we've now run into an issue where an address may disappear from DAWA. According to the documentation, addresses may have status 2 or 4, in which case the don't appear in DAWA. What the documentation may hint at, but does not say explicitly, is that addresses may change and _get_ this status. Hence, they simply disappear. One such example is `bd7e5317-4a9e-437b-8923-11156406b117` in Ballerup which we've used for testing.

One obvious solution is using the experimental history API. Unfortunately, it contains rather limited data compared to the normal API, with notable exclusions being the actual string description of the address as well as its geographical location, i.e. coordinates.

I should note that we actually know the time both when we stored the address and when it was intended to take effect. As a result, we can specify a time at which the address existed, if that where possible.

On a final note, I'd like to say that I was pleasantly surprised when I first discovered DAR/DAWA — it's a very nice project and product, and having an authoritative source for all address data in the country is truly awesome. However, that's precisely why I was disappointed to discover that you can't assume that an address resolved in DAWA remains resolvable.

I hope you can be of assistance — thank you!

**Comment by andershessellund** [comment]
This will be fixed by a new parameter "medtagnedlagte", which will cause the response to include adresses with status 2 and 4.
