### ISSUE TITLE
Unable to acquire actual address for Engtoften 4, 8260 VIBY J

### ISSUE THREAD

**Issue by JosephWLW** [DanmarksAdresser/Dawa#679]
Hi Guys in DAWA,

Good day.
We are unable to acquire the correct "adressebetegnelse" for the address below:
Engtoften 4, 8260 VIBY J

Steps to reproduce issue:
1. Navigate to https://dawa.aws.dk/datavask/adresser?betegnelse=Engtoften%204,%208260%20VIBY%20J
2. Under "resultater", navigate to the first href acquire: 
https://dawa.aws.dk/adresser/0a3f50c2-cbde-32b8-e044-0003ba298018
3. Under the property of "adressebetegnelse", the address returned are:
Engtoften 3, 1. 4, 8260 Viby J
Which is the address at the opposite road.

Questions:
1. Can we know if there is any reason causing the returned address to be different with the one entered?
2. Is there any way for us to get a more accurate address than the one returned?

**Comment by andershessellund** [comment]
The address "Engtoften 4, 8260 Viby J" does not exist. There are also no historic records of this address, although it may have existed before historic records were kept.

There is an address "Engtoften 4A, 8260 Viby J".
