### ISSUE TITLE
Dawa returnerer ikke korrekte geometrier for jordstykker.

### ISSUE THREAD

**Issue by klavspc** [DanmarksAdresser/Dawa#697]
Dawa leverer simplificerede geometrier for jordstykker således, at jordstykker overlapper hinanden. Det betyder, at en efterfølgende analyse af et jordstykke i f.eks. GIS giver et resultat som er misvisende. Det er klart, at decimaler skal skæres et-eller-andet sted, men burde sdfe's tjenester ikke levere samme data?

Følgende kald til dawa returnerer jordstykke med geometri med to decimaler: https://dawa.aws.dk/jordstykker/2008451/4732?format=geojson&srid=25832

Følgende kald til til kortforsyningens restGeoKeys returnerer geometri med tre decimaler: https://kortforsyningen.kms.dk/?servicename=RestGeokeys_v2&method=matrikelnr&f=json&geometry=true&ejkode=2008451&matnr=4732&login=xxx&password=xxx

```
{
 "type": "FeatureCollection",
 "crs": {
  "type": "name",
  "properties": {"name": "EPSG:25832"}
 },
 "features": [{
  "type": "Feature",
  "properties": {
   "matnr": "4732",
   "centroid_x": 552577.338,
   "centroid_y": 6083870.25,
   "ejerlav_kode": 2008451,
   "ejerlav_navn": "Sønderborg",
   "ejerlav_href": "https:\/\/services.kortforsyningen.dk\/?servicename=RestGeokeys_v2&method=ejerlav&ejkode=2008451"
  },
  "bbox": [
   552557.801,
   6083857.844,
   552596.563,
   6083883.726
  ],
  "geometry": {
   "type": "Polygon",
   "coordinates": [[
    [
     552559.563,
     6083857.844
    ],
    [
     552596.563,
     6083859.859
    ],
    [
     552595.507,
     6083880.708
    ],
    [
     552591.689,
     6083883.726
    ],
    [
     552557.801,
     6083879.251
    ],
    [
     552559.563,
     6083857.844
    ]
   ]]
  }
 }]
}

```

**Comment by andershessellund** [comment]
Hej Klavs,

Tak for din henvendelse. Vi vil rette det til næste release således at alle decimaler vil blive returneret for jordstykker.

Som midlertidigt workaround kan du slå jordstykkerne op på vores replikerings-API:
https://dawa.aws.dk/replikering/udtraek?entitet=jordstykke&ejerlavkode=2008451&matrikelnr=4732
