### ISSUE TITLE
Manglende skema i DDL fra replikeringsklient

### ISSUE THREAD

**Issue by AsgerPetersen** [DanmarksAdresser/Dawa#731]
`dawa-replication-client` i version `1.3.2`.

Generer konfiguration med 
```sh
$ dawa-replication-client gen-config --file my-config.json
```

Fjern alle andre entiteter end `adresse` og ændr skema, så `my-config.json` ser således ud
```json
{
  "replication_url": "https://dawa.aws.dk/replikering",
  "replication_schema": "dawa",
  "entities": [
    {
      "name": "adresse",
      "attributes": [
        "id",
        "status",
        "oprettet",
        "ændret",
        "ikrafttrædelsesdato",
        "adgangsadresseid",
        "etage",
        "dør",
        "kilde",
        "esdhreference",
        "journalnummer"
      ]
    }
  ],
  "bindings": {
    "adresse": {
      "table": "adresse"
    }
  }
}
```

Generer DDL med 
```sh
$ dawa-replication-client gen-schema --replication-config my-config.json --file schema.sql
```

`schema.sql` ser nu således ud:
```postgresql
CREATE SCHEMA IF NOT EXISTS dawa;
CREATE TABLE dawa.transactions(
  txid integer PRIMARY KEY,
  ts timestamptz);
CREATE TABLE dawa.source_transactions(
  source_txid integer,
  local_txid integer NOT NULL,
  entity text NOT NULL,
  type text NOT NULL,
  PRIMARY KEY (source_txid, entity));
CREATE TYPE dawa.operation_type AS ENUM ('insert', 'update', 'delete');
create table adresse(
id uuid,
status integer,
oprettet timestamp,
ændret timestamp,
ikrafttrædelsesdato timestamp,
adgangsadresseid uuid,
etage text,
dør text,
kilde integer,
esdhreference text,
journalnummer text,
PRIMARY KEY(id)
)
```

Bemærk, at tabellen `adresse` oprettes uden skema.

**Comment by AsgerPetersen** [comment]
Aaah, ved nærlæsning af dokumentationen ser jeg, at det kun er **metadata**, som man kan styre skemaet på.

Det ville være virkelig fedt, hvis man også kunne styre, hvilket skema data skrives i.

Der må være mange use cases, hvor man har brug for at have replikerede dawa data i samme database som andre data.

I vores tilfælde ville vi gerne indlæse dawa-data i en database med adskillige andre datasæt. Derfor vil vi meget gerne kunne udnytte skemaer til at strukturere data og styre rettigheder.

**Comment by andershessellund** [comment]
Det er egentlig med vilje, at data-tabellerne placeres i public schema, og det kun er metadatatabellerne som replikeringsklienten anvender, der placeres i et andet schema. Begrundelsen er, at metadatatabellerne er af en "intern" karakter, og det således kan være uhensigtsmæssigt at placere dem i public.

Hvis du ønsker, så kan du selv tilpasse den genererede konfiguration, således at tabellen placeres i et andet schema. Det gøres ved at ændre "table" attributten til eksempelvis "dawa_replication.adresse" i stedet for "adresse".

Hvis der generelt er et ønske om at kunne generere en konfiguration hvor også data-tabellerne placeres i et andet schema en public, så vil vi også gerne implementere support for det.

**Comment by AsgerPetersen** [comment]
@andershessellund tak for hurtigt svar! Jeg har allerede oprettet et feature request i #732 😀

**Comment by AsgerPetersen** [comment]
@andershessellund og det virker jo som en drøm at sætte skemaet i `table`-attributten. Tak.
