### ISSUE TITLE
Hvilket adressepunkt bliver der anvendt til at afgøre hvorvidt adressen ligger inden for en polygon i autocomplete?

### ISSUE THREAD

**Issue by finnjordal** [DanmarksAdresser/Dawa#770]
Adgangspunkt eller vejpunkt?
Det ser ud til at det er vejpunkt.

**Comment by andershessellund** [comment]
Det er en fejl. Jeg har tilføjet "geometri" parameteren til autocomplete, så man kan vælge mellem "adgangspunkt" eller "vejpunkt" - default er "adgangspunkt"
