### ISSUE TITLE
Kan ikke vælge standardformat ved anvendelse af autocomplete

### ISSUE THREAD

**Issue by finnjordal** [DanmarksAdresser/Dawa#777]
http://dawa-test.aws.dk/adresser?autocomplete&q=r%C3%B8d&format=json

**Comment by andershessellund** [comment]
Man skal bruge struktur=nestet

**Comment by finnjordal** [comment]
Måske skulle vi ikke have haft mini muligheden under struktur, men det kan vi ikke gøre noget ved nu.
