### ISSUE TITLE
Vejnavnesøgningen respekterer ikke kommunekode

### ISSUE THREAD

**Issue by klavspc** [DanmarksAdresser/Dawa#782]
https://dawa.aws.dk/vejnavne?q=slesvi*&kommunekode=0101 returnerer navne fra tre kommuner og ikke kun 0101 (Københavns kommune):

```
[
{
  "href": "https://dawa.aws.dk/vejnavne/Slesvigsgade",
  "navn": "Slesvigsgade",
  "postnumre": [
    {
      "href": "https://dawa.aws.dk/postnumre/7000",
      "nr": "7000",
      "navn": "Fredericia"
    },
    {
      "href": "https://dawa.aws.dk/postnumre/8800",
      "nr": "8800",
      "navn": "Viborg"
    },
    {
      "href": "https://dawa.aws.dk/postnumre/1762",
      "nr": "1762",
      "navn": "København V"
    }
  ],
  "kommuner": [
    {
      "href": "https://dawa.aws.dk/kommuner/0607",
      "kode": "0607",
      "navn": "Fredericia"
    },
    {
      "href": "https://dawa.aws.dk/kommuner/0791",
      "kode": "0791",
      "navn": "Viborg"
    },
    {
      "href": "https://dawa.aws.dk/kommuner/0101",
      "kode": "0101",
      "navn": "København"
    }
  ]
}
]
```

**Comment by andershessellund** [comment]
Hej Klavs,

Vejnavnesøgningen fungerer sådan, at den filtrerer vejnavnet på kommunekode, dvs. man modtager de vejnavne, som findes i den pågældende kommune.

Filtreringsparametrene ændrer ikke på svarstrukuren der kommer tilbage for et givet vejnavn, dvs. alle kommuner og postnumre for vejnavnet er med uanset om man filtrerer via kommunekode.

En løsning på det du efterspørger kunne være at anvende vejstykke API'et i stedet, når du filtrerer på kommunekode. Så får du kun de postnumre der findes indenfor den kommune du angiver.

**Comment by klavspc** [comment]
Jeg forstår svaret, men synes stadig det er kontraintituitivt.

__Men__: er det ikke noget, der har ændret sig for ganske nylig? Jeg har på een dag fået fejlmeldinger fra tre kunder vedr vores søgekomponent.

**Comment by andershessellund** [comment]
Jeg erindrer ikke, at der har været ændringer i dette. Jeg kan godt forstå, at det kan virke kontraintuitivt i forbindelse med vejnavne, men det er mest fordi at vejnavne er en slags pseudoentitet, som er lidt svær at forholde sig til.

Vi har i princippet en parallel opførsel på navngiven vej. Den har jo indlejet NavngivenVejKommunedel på tilsvarende vis som Vejnavne har indlejrede kommuner, men for NavngivenVej er det mere tydeligt det ikke ville give mening at filtere i de indlejrede NavgivenVejKommundel, hvis man anvender kommunekode-parameteren.

Vi har planer om at udstille NavngivenVejPostnummerrelation med autocomplete-funktionalitet (#740) . Hvert svar i denne autocomplete vil være en unik kombination af NavngivenVej og Postnummer. Hvis vi så laver understøttelse for kommunekode-parameteren i denne også, så tænker jeg måske du får den søgefunktionalitet, som jeres kunder forventer?

**Comment by klavspc** [comment]
> Jeg erindrer ikke, at der har været ændringer i dette

@andershessellund: Hej Anders - kan du ringe til mig? Jeg har en formodning om at ændringen i vejnavne-API kan være sket i `sqModel.js` i _Konsolidering af autocomplete_. Direkte link: https://github.com/DanmarksAdresser/Dawa/commit/1dcc113d61ece59028aefaadd7fba73b0196fb60#diff-dbf8754a5d9ea95e12c80197203c8220. (EXISTS istedet for det tidligere simplere JOIN mod kommuner og postnumre)

**Comment by klavspc** [comment]
> En løsning på det du efterspørger kunne være at anvende vejstykke API'et i stedet, når du filtrerer på kommunekode. Så får du kun de postnumre der findes indenfor den kommune du angiver.

Jeg er i gang med at lægge om til at dele af min søgning nu bruger vejstykke API'et, når jeg filtrerer på kommunekode. Det er et skridt på vejen, men sorteringen er tydeligvis på vejkode og det er svært at præsentere for brugeren. (Jeg så gerne sortering på navn). Har forsøgt at bruge autocomplete-parameteren, men den sorterer heller ikke på navn (og her ville det virkelig give mening) og desuden returneres der ikke postnumre ved autocomplete.

Derfor: Jeg så gerne at vejstykker sorteres efter navn, alternativt at man kan angive sortering i kaldet.

**Comment by andershessellund** [comment]
Hej Klavs, jeg kan godt se det giver mening med sortering efter navn. Af tekniske årsager sorterer vi dog efter entitetens primære nøgle, og for vejstykker er det (kommunekode, vejkode). 

Undtagelsen er ved anvendelse af søgeparameteren, q, hvor der sker en ranking af søgeresultatet.

Jeg vil oprette et issue på sortering efter navn.

I den nye release kan du benytte autocomplete parameteren sammen med struktur-parameteren, og dermed få postnumre med tilbage hvis du ønsker.
