### ISSUE TITLE
Vejnavne: Relation til postnumre baseres på navngivenvejs postnummerrelation

### ISSUE THREAD

**Issue by klavspc** [DanmarksAdresser/Dawa#783]
https://dawa.aws.dk/vejnavne?kommunekode=0101&q=verdis* returnerer Københavns kommune (blandt flere kommuner se #782 ), men ingen postnumre i kommunen:

```
[
{
  "href": "https://dawa.aws.dk/vejnavne/Verdisvej",
  "navn": "Verdisvej",
  "postnumre": [
    {
      "href": "https://dawa.aws.dk/postnumre/7400",
      "nr": "7400",
      "navn": "Herning"
    },
    {
      "href": "https://dawa.aws.dk/postnumre/9700",
      "nr": "9700",
      "navn": "Brønderslev"
    },
    {
      "href": "https://dawa.aws.dk/postnumre/9200",
      "nr": "9200",
      "navn": "Aalborg SV"
    },
    {
      "href": "https://dawa.aws.dk/postnumre/8920",
      "nr": "8920",
      "navn": "Randers NV"
    },
    {
      "href": "https://dawa.aws.dk/postnumre/4200",
      "nr": "4200",
      "navn": "Slagelse"
    }
  ],
  "kommuner": [
    {
      "href": "https://dawa.aws.dk/kommuner/0101",
      "kode": "0101",
      "navn": "København"
    },
    {
      "href": "https://dawa.aws.dk/kommuner/0657",
      "kode": "0657",
      "navn": "Herning"
    },
    {
      "href": "https://dawa.aws.dk/kommuner/0810",
      "kode": "0810",
      "navn": "Brønderslev"
    },
    {
      "href": "https://dawa.aws.dk/kommuner/0851",
      "kode": "0851",
      "navn": "Aalborg"
    },
    {
      "href": "https://dawa.aws.dk/kommuner/0730",
      "kode": "0730",
      "navn": "Randers"
    },
    {
      "href": "https://dawa.aws.dk/kommuner/0330",
      "kode": "0330",
      "navn": "Slagelse"
    }
  ]
}
]
```

**Comment by klavspc** [comment]
Jeg er med på at grunden til at Dawa ikke finder postnummer 2450 for Verdisvej i København sikkert er at der ikke er nogen adresser på vejen, men det _burde_ ikke være sådan.


- navngivne veje _har_ postnummer,
- det er en navne-søgning, ikke en adressesøgning og
- man kan endda angive postnummer som parameter til søgningen

**Comment by andershessellund** [comment]
Hej Klavs,

Din begrundelse for den nuværende opførsel er korrekt. Den er historisk begrundet - oprindeligt var der jo ikke nogen navngivne veje, og der var heller ikke nogen kilde til relationen mellem vejstykker og postnumre. Så vi beregnede dem ud fra det bedste datagrundlag vi havde på det tidspunkt, dvs. adresserne.

Det ville give god mening hvis relationen mellem vejnavne og postnumre blev baseret på navngivenvejs postnummerrelation i stedet for adresser. Det vil blive implementeret, men jeg kan p.t. ikke give nogen tidshorisont på det.
