### ISSUE TITLE
vejnavne-søgning: tomt vejnavn uden postnumre

### ISSUE THREAD

**Issue by klavspc** [DanmarksAdresser/Dawa#830]
https://dawa.aws.dk/vejnavne?q=&side=1&per_side=10&kommunekode=163 returnerer som første objekt tomt vejnavn uden postnumre. Det sker både uden _kommunekode_-parameter og med een af de nævnte kommunekoder.

Både [vejstykker ](https://dawa.aws.dk/vejstykker?q=&side=1&per_side=4&noformat=1)og [autocomplete ](https://dawa.aws.dk/adgangsadresser/autocomplete?q=&type=adgangsadresse&side=1&per_side=4&noformat=1&srid=25832)kan kaldes med blank query og returnerer meningsfulde data

```
{
	href: "https://dawa.aws.dk/vejnavne/",
	navn: "",
	postnumre: [],
	kommuner: [{
			href: "https://dawa.aws.dk/kommuner/0163",
			kode: "0163",
			navn: "Herlev"
		},
		{
			href: "https://dawa.aws.dk/kommuner/0169",
			kode: "0169",
			navn: "Høje-Taastrup"
		},
		{
			href: "https://dawa.aws.dk/kommuner/0173",
			kode: "0173",
			navn: "Lyngby-Taarbæk"
		},
		{
			href: "https://dawa.aws.dk/kommuner/0219",
			kode: "0219",
			navn: "Hillerød"
		},
		{
			href: "https://dawa.aws.dk/kommuner/0230",
			kode: "0230",
			navn: "Rudersdal"
		},
		{
			href: "https://dawa.aws.dk/kommuner/0340",
			kode: "0340",
			navn: "Sorø"
		},
		{
			href: "https://dawa.aws.dk/kommuner/0350",
			kode: "0350",
			navn: "Lejre"
		},
		{
			href: "https://dawa.aws.dk/kommuner/0550",
			kode: "0550",
			navn: "Tønder"
		},
		{
			href: "https://dawa.aws.dk/kommuner/0561",
			kode: "0561",
			navn: "Esbjerg"
		},
		{
			href: "https://dawa.aws.dk/kommuner/0851",
			kode: "0851",
			navn: "Aalborg"
		}
	]
}
```
Resultatet kan ses på http://search.cdn.septima.dk/5.5.0/examples/simple.dk/:
![image](https://user-images.githubusercontent.com/3736091/70223033-3bb62400-174b-11ea-96fb-674294b7f473.png)

**Comment by klavspc** [comment]
Det tomme vejnavn er i øvrigt en ny ting, der kom med forrige opdatering (små to uger siden skyder jeg på).

**Comment by andershessellund** [comment]
Det er en klar fejl, som vil blive rettet til næste release.
