### ISSUE TITLE
Spatiale indexer i replikeringsklienten

### ISSUE THREAD

**Issue by elvios** [DanmarksAdresser/Dawa#841]
Naar jeg replikerer data igennem replikeringsklienten, kommer der ikke nogle spatiale indexer paa geometri-kolonnerne.

Vil det give mening, at man selv kan vaelge hvilke geometri-kolonner, der skal spatiale indexer paa? Maaske igennem config.json-filen.

**Comment by andershessellund** [comment]
Replikerings-klienten opretter kun de indexes som er nødvendige for replikerings-klientens funktionalitet. Jeg tror ikke det giver mening at replikeringsklienten opretter yderligere indexes, for der er så mange forskellige brugsscenarier for data, men det er heldigvis ikke noget problem at oprette dem selv.

Du skal dog være opmærksom på, at Postgres' spatiale index er meget ineffektive for store geometrier som f.eks. regioner og kommuner. I DAWA-regi laver vi derfor en separat tabel, hvor de store geometrier er opdelt i mindre geometrier der kan indekseres og bruges til geokodning.
