### ISSUE TITLE
Problem med autocomplete

### ISSUE THREAD

**Issue by finnjordal** [DanmarksAdresser/Dawa#854]
"http://dawa-p2.aws.dk/autocomplete?q=vej 1 1" returnerer vejnavn og ikke adgangsadresser. Der findes en adgangsadresse med vejnavn Vej 1 og husnummer 1.
"http://dawa-p2.aws.dk/autocomplete?q=vej 1 2" returnerer adgansadresser til trods for at der ikke findes en adgangsadresse med vejnavn Vej 1 og husnummer 2

Det er først efter indtastning af "vej 1 1 2" Vej 1 1, 2000 Frederiksberg dukker op

**Comment by andershessellund** [comment]
Problemet med første query er, at query'et "vej 1 1" matcher rigtigt mange adresser (ca. 1800). Det giver os et problem, for vores autocomplete algoritme er sådan, at vi kun ranker de første 1000 resultater - og der er den rigtige adresse ikke mellem.

Jeg har øget grænsen til 2000 for vores "two pass" autocomplete. Det burde kun have negative performance-implikationer i meget få tilfælde.
