### ISSUE TITLE
Adgangsadresse datavask returnere ikke en aktueladresse

### ISSUE THREAD

**Issue by madssta** [DanmarksAdresser/Dawa#862]
Adressen " Asmusgårdsvej 4, , 8520 Lystrup" retunere ikke nogle aktueladress ved Adgangsadresse datavask. Se link [https://dawa.aws.dk/datavask/adgangsadresser?betegnelse=Asmusg%C3%A5rdsvej%204,%20,%208520%20Lystrup](https://dawa.aws.dk/datavask/adgangsadresser?betegnelse=Asmusg%C3%A5rdsvej%204,%20,%208520%20Lystrup)

**Comment by finnjordal** [comment]
Hej Mads
Tak for din fejlmelding.
Det er helt klart en fejl, som vi vil se på.

**Comment by finnjordal** [comment]
Fejlen er nu rettet: https://dawa.aws.dk/datavask/adgangsadresser?betegnelse=Asmusg%C3%A5rdsvej%204,%20,%208520%20Lystrup&cache=no-cache
